language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - build-tools-28.0.2
    - build-tools-27.0.3
    - build-tools-26.0.2
    - build-tools-25.0.2
    - build-tools-25.0.0
    - android-29
    - android-28
    - android-27
    - android-26
    - android-25
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - '.+'

install:
  # Check install section: http://docs.travis-ci.com/user/build-configuration/#install
  # If you'd like to skip the install stage entirely, set it to true and nothing will be run.
  - true

jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
- chmod +x gradlew
- ./gradlew build connectedCheck
