language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - build-tools-28.0.2
    - android-29
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - '.+'

install:
  # Check install section: http://docs.travis-ci.com/user/build-configuration/#install
  # If you'd like to skip the install stage entirely, set it to true and nothing will be run.
  - true

jdk:
  - oraclejdk8

script:
- chmod +x gradlew
- ./gradlew build connectedCheck
