name: Android CI

on:
  push:
    branches: [ "v3" ]
  pull_request:
    branches: [ "v3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
      run: ./gradlew assembleDebug
    - name: Upload APK Debug - ${{ env.repository_name }}
      uses: actions/upload-artifact@v3
      with:
       name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) debug generated
       path: ${{ env.main_project_module }}/build/outputs/apk/debug/
          
